### PR TITLE
fix issue#1: decoupling of files and code organization

### PR DESCRIPTION
**Pull request by rheimon1**

### CODE REVIEW

**Comment by Gimenz** [comment]
> _No description provided._

it worked, but the results are not displayed
2020-10-05 04_10_22-Window

**Comment by rheimon1** [comment]
Hey, @Gimenz! The error is related to the library cheerio, I'm gonna try to help you.

**Comment by Gimenz** [comment]
> Hey, @Gimenz! The error is related to the library cheerio, I'm gonna try to help you.

thank you for helping. sorry, i am still learning for this

**Comment by khai93** [comment]
I've fixed this new issue that popped up in my PR!

**Pull request merged**
